// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoCrud.Data;

#nullable disable

namespace ProjetoCrud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910123130_AddIdLoginToPaciente")]
    partial class AddIdLoginToPaciente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoCrud.Models.CONEVENIO_TAB_STATUS", b =>
                {
                    b.Property<int>("ID_PAC_TAB_CONVENIO_STATUS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PAC_TAB_CONVENIO_STATUS_DESCRICAO")
                        .HasColumnType("longtext");

                    b.HasKey("ID_PAC_TAB_CONVENIO_STATUS");

                    b.ToTable("CONEVENIO_TAB_STATUS");
                });

            modelBuilder.Entity("ProjetoCrud.Models.LOGIN", b =>
                {
                    b.Property<int>("id_USER")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CARGO")
                        .HasColumnType("longtext");

                    b.Property<string>("EMAIL")
                        .HasColumnType("longtext");

                    b.Property<string>("SENHA")
                        .HasColumnType("longtext");

                    b.HasKey("id_USER");

                    b.ToTable("LOGIN");
                });

            modelBuilder.Entity("ProjetoCrud.Models.MED_AGENDA", b =>
                {
                    b.Property<int>("ID_MED_AGENDASUPERKEY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ID_MED_CRM")
                        .HasColumnType("int");

                    b.Property<int>("ID_MED_TAB_AGENDA_PERIODO")
                        .HasColumnType("int");

                    b.Property<string>("MED_AGENDA_DIA_SEMANA")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("MED_AGENDA_HORA_FINAL")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("MED_AGENDA_HORA_INICIAL")
                        .HasColumnType("time(6)");

                    b.Property<int>("MED_AGENDA_QTDE_MAXIMA")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("MED_AGENDA_TEMPO_CONSULTA")
                        .HasColumnType("time(6)");

                    b.HasKey("ID_MED_AGENDASUPERKEY");

                    b.ToTable("MED_AGENDA");
                });

            modelBuilder.Entity("ProjetoCrud.Models.MED_AGENDAMENTO", b =>
                {
                    b.Property<int>("ID_MED_AGENDAMENTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ID_MED_AGENDAMENTO_STATUS")
                        .HasColumnType("int");

                    b.Property<int>("ID_MED_CRM")
                        .HasColumnType("int");

                    b.Property<int>("ID_MED_TAB_AGENDA_PERIODO")
                        .HasColumnType("int");

                    b.Property<int>("ID_PAC_RG_CIN")
                        .HasColumnType("int");

                    b.Property<DateTime>("MED_AGENDAMENTO_DATA")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("MED_AGENDAMENTO_HORARIO")
                        .HasColumnType("time(6)");

                    b.HasKey("ID_MED_AGENDAMENTO");

                    b.ToTable("MED_AGENDAMENTO");
                });

            modelBuilder.Entity("ProjetoCrud.Models.MED_AGENDAMENTO_STATUS", b =>
                {
                    b.Property<int>("ID_MED_AGENDAMENTO_STATUS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MED_AGENDAMENTO_STATUS_DESCRICAO")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_AGENDAMENTO_STATUS_OCULTA")
                        .HasColumnType("longtext");

                    b.HasKey("ID_MED_AGENDAMENTO_STATUS");

                    b.ToTable("MED_AGENDAMENTO_STATUS");
                });

            modelBuilder.Entity("ProjetoCrud.Models.MED_MEDICO_DADOS", b =>
                {
                    b.Property<int>("ID_MED_CRM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ID_MED_TAB_ESPECIALIDADE")
                        .HasColumnType("int");

                    b.Property<int>("ID_MED_TAB_STATUS")
                        .HasColumnType("int");

                    b.Property<string>("MED_BAIRRO")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_CEP")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_CIDADE")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_COMPLEMENTO")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_ENDERECO")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_NOME_COMPLETO")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_NUMERO")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_SEXO")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_TELEFONE")
                        .HasColumnType("longtext");

                    b.Property<string>("MED_UF")
                        .HasColumnType("longtext");

                    b.HasKey("ID_MED_CRM");

                    b.ToTable("MED_MEDICO_DADOS");
                });

            modelBuilder.Entity("ProjetoCrud.Models.MED_PACIENTE", b =>
                {
                    b.Property<int>("ID_PAC_RG_CIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ID_LOGIN")
                        .HasColumnType("int");

                    b.Property<int>("ID_PAC_TAB_CONVENIO")
                        .HasColumnType("int");

                    b.Property<string>("PAC_BAIRRO")
                        .HasColumnType("longtext");

                    b.Property<string>("PAC_CEP")
                        .HasColumnType("longtext");

                    b.Property<string>("PAC_CIDADE")
                        .HasColumnType("longtext");

                    b.Property<string>("PAC_COMPLEMENTO")
                        .HasColumnType("longtext");

                    b.Property<string>("PAC_CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("PAC_ENDERECO")
                        .HasColumnType("longtext");

                    b.Property<string>("PAC_NOME_COMPLETO")
                        .HasColumnType("longtext");

                    b.Property<string>("PAC_NUMERO")
                        .HasColumnType("longtext");

                    b.Property<string>("PAC_SEXO")
                        .HasColumnType("longtext");

                    b.Property<string>("PAC_TELEFONE")
                        .HasColumnType("longtext");

                    b.Property<string>("PAC_UF")
                        .HasColumnType("longtext");

                    b.HasKey("ID_PAC_RG_CIN");

                    b.HasIndex("ID_LOGIN");

                    b.ToTable("MED_PACIENTE");
                });

            modelBuilder.Entity("ProjetoCrud.Models.MED_TAB_AGENDA_PERIODO", b =>
                {
                    b.Property<int>("ID_MED_TAB_AGENDA_PERIODO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MED_TAB_AGENDA_PERIODO_DESCRICAO")
                        .HasColumnType("longtext");

                    b.Property<bool>("MED_TAB_AGENDA_PERIODO_OCULTA")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID_MED_TAB_AGENDA_PERIODO");

                    b.ToTable("MED_TAB_AGENDA_PERIODO");
                });

            modelBuilder.Entity("ProjetoCrud.Models.MED_TAB_ESPECIALIDADE", b =>
                {
                    b.Property<int>("ID_MED_TAB_ESPECIALIDADE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MED_TAB_ESPECIALIDADE_DESCRICAO")
                        .HasColumnType("longtext");

                    b.Property<bool>("MED_TAB_ESPECIALIDADE_OCULTA")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID_MED_TAB_ESPECIALIDADE");

                    b.ToTable("MED_TAB_ESPECIALIDADE");
                });

            modelBuilder.Entity("ProjetoCrud.Models.MED_TAB_STATUS", b =>
                {
                    b.Property<int>("ID_MED_TAB_STATUS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MED_TAB_STATUS_DESCRICAO")
                        .HasColumnType("longtext");

                    b.Property<bool>("MED_TAB_STATUS_OCULTA")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID_MED_TAB_STATUS");

                    b.ToTable("MED_TAB_STATUS");
                });

            modelBuilder.Entity("ProjetoCrud.Models.PAC_TAB_CONVENIO", b =>
                {
                    b.Property<int>("ID_PAC_TAB_CONVENIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ID_PAC_TAB_CONVENIO_STATUS")
                        .HasColumnType("int");

                    b.Property<string>("PAC_TAB_CONVENIO_DESCRICAO")
                        .HasColumnType("longtext");

                    b.Property<bool>("PAC_TAB_CONVENIO_OCULTA")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID_PAC_TAB_CONVENIO");

                    b.ToTable("PAC_TAB_CONVENIO");
                });

            modelBuilder.Entity("ProjetoCrud.Models.MED_PACIENTE", b =>
                {
                    b.HasOne("ProjetoCrud.Models.LOGIN", "Login")
                        .WithMany()
                        .HasForeignKey("ID_LOGIN");

                    b.Navigation("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
